Update print.yaml

diff --git a/.github/workflows/print.yaml b/.github/workflows/print.yaml
--- a/.github/workflows/print.yaml
+++ b/.github/workflows/print.yaml
@@ -26,10 +26,11 @@ jobs:
        - name: Validate env
          id: validate_env
          run: |
-           if [[ "${{ env.PROFILE }}" != "develop" && "${{ env.PROFILE }}" != "main" && "${{ env.PROFILE }}" != "stage" && "${{ env.PROFILE }}" != "test" && "${{ env.PROFILE }}" != "feature_*_fastlane" ]]; then
-             echo "Invalid PROFILE value: ${{ env.PROFILE }}"
-             exit 1
-           fi
+            if [[ "${{ env.PROFILE }}" != "develop" && "${{ env.PROFILE }}" != "main" && "${{ env.PROFILE }}" != "stage" && "${{ env.PROFILE }}" != "test" && "${{ env.PROFILE }}" != "feature_*_fastlane" ]]; then
+              echo "Invalid PROFILE value: ${{ env.PROFILE }}
+              branch name shall be either develop/stage/test/main or feature_*_fastlane to trigger the mobile builds"
+              exit 1
+            fi
  
        - name: print env
          run: echo "${{ env.PROFILE }}"
