Update print.yaml

diff --git a/.github/workflows/print.yaml b/.github/workflows/print.yaml
--- a/.github/workflows/print.yaml
+++ b/.github/workflows/print.yaml
@@ -17,12 +17,21 @@ jobs:
        - name: Determine env
          id: determine_env
          run: |
-           PROFILE=$(echo $GITHUB_REF | cut -d'/' -f3)
-           # Check if PROFILE is one of the valid values; otherwise, set it to 'develop'
-           if [[ "$PROFILE" != "develop" && "$PROFILE" != "stage" && "$PROFILE" != "test" && "$PROFILE" != "main" ]]; then
-             PROFILE="develop"
-           fi
-           echo "PROFILE=${PROFILE}" >> $GITHUB_ENV
+            PROFILE=$(echo $GITHUB_REF | cut -d'/' -f3)
+            # Check if PROFILE is one of the valid values; otherwise, set it to 'develop'
+            if [[ "$PROFILE" = feature_*_fastlane ]]; then
+              PROFILE="develop"
+            fi
+            echo "PROFILE=${PROFILE}" >> $GITHUB_ENV
 
-       - name: Print env
+       - name: Validate env
+         id: validate_env
+         run: |
+            if [[ "${{ env.PROFILE }}" != "develop" && "${{ env.PROFILE }}" != "main" && "${{ env.PROFILE }}" != "stage" && "${{ env.PROFILE }}" != "test" && "${{ env.PROFILE }}" != "feature_*_fastlane" ]]; then
+              echo "Invalid PROFILE value: ${{ env.PROFILE }} \n
+              branch name shall be either develop/stage/test/main or feature_*_fastlane to trigger the mobile builds"
+              exit 1
+            fi
+ 
+       - name: print env
          run: echo "${{ env.PROFILE }}"
