Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -25,8 +25,9 @@ jobs:
          id: validate_env
          run: |
            if [[ "${{ env.PROFILE }}" != "develop" && "${{ env.PROFILE }}" != "main" && "${{ env.PROFILE }}" != "stage" && "${{ env.PROFILE }}" != "test" && "${{ env.PROFILE }}" != "feature_*_fastlane" ]]; then
-             echo "Invalid PROFILE value: ${{ env.PROFILE }}"
-             exit 1
+              echo "Invalid PROFILE value: ${{ env.PROFILE }} \n
+              branch name shall be either develop/stage/test/main or feature_*_fastlane to trigger the mobile builds"
+              exit 1
            fi
  
        - name: print env
